[project]
name = "syndication-python-template"
version = "0.1.0"
description = "Example Python/FastAPI application that handles the Cloudesire syndication API"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi-slim==0.115.6",
    "httpx==0.28.1",
    "pydantic-settings==2.7.1",
    "python-dotenv==1.0.1",
]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "respx>=0.21.1",
    "ruff>=0.8.2",
]
