[project]
name = "syndication-python-template"
version = "0.1.0"
description = "Example Python/FastAPI application that handles the Cloudesire syndication API"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi-slim==0.115.12",
    "httpx==0.28.1",
    "pydantic-settings==2.9.1",
    "python-dotenv==1.1.0",
]

[dependency-groups]
dev = [
    "pytest==8.3.5",
    "respx==0.22.0",
    "ruff==0.11.13",
]
